name: Deploy to VPS

on:
  push:
    branches:
      - main # Atur branch yang akan memicu deploy, misalnya 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Copy code to VPS
        env:
          VPS_HOST: ${{ secrets.VPS_HOST }}
          VPS_USER: ${{ secrets.VPS_USER }}
          VPS_PASSWORD: ${{ secrets.VPS_PASSWORD }}
        run: |
          sshpass -p $VPS_PASSWORD ssh -o StrictHostKeyChecking=no $VPS_USER@$VPS_HOST << 'EOF'
            mkdir -p /home/$VPS_USER/project/chatbot-pmb-undiksha
            cd /home/$VPS_USER/project/chatbot-pmb-undiksha || git clone https://github.com/odetv/chatbot-pmb-undiksha.git /home/$VPS_USER/project/chatbot-pmb-undiksha
            git pull origin main
            source venv/bin/activate || python3 -m venv venv && source venv/bin/activate
            pip install --no-cache-dir -r requirements.txt
            pkill -f 'uvicorn main:app' || true
            nohup uvicorn main:app --host 0.0.0.0 --port 1014 &
          EOF
